"""empty message

Revision ID: 41338caea0fc
Revises: 0a34c8e422f5
Create Date: 2021-12-22 16:31:32.645642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41338caea0fc'
down_revision = '0a34c8e422f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('create_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'create_date')
    # ### end Alembic commands ###
